-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."SequelizeMeta"
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "SequelizeMeta_pkey" PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public."Shipments"
(
    shipmentid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    clientid integer,
    revenue numeric(10, 2),
    createdat timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp without time zone NOT NULL,
    "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp without time zone DEFAULT now(),
    "clientId" integer NOT NULL,
    "currentLocation" geometry,
    CONSTRAINT "Shipments_pkey" PRIMARY KEY (shipmentid)
);

CREATE TABLE IF NOT EXISTS public.addresses
(
    address_id serial NOT NULL,
    user_id integer,
    street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(50) COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    country character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_default boolean DEFAULT false,
    CONSTRAINT addresses_pkey PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS public.invoices
(
    id serial NOT NULL,
    client_id integer,
    order_id integer,
    invoice_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    due_date date NOT NULL,
    amount numeric(12, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    user_id integer,
    order_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total_amount numeric(10, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_id integer,
    quantity integer NOT NULL,
    price_per_unit numeric(10, 2) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.password_resets
(
    id serial NOT NULL,
    user_id integer,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    CONSTRAINT password_resets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    order_id integer,
    user_id integer,
    amount numeric(10, 2) NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    payment_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Not Yet Paid'::character varying,
    invoice_id integer,
    payment_date date,
    days_late integer DEFAULT 0,
    payment_timing character varying(20) COLLATE pg_catalog."default" DEFAULT 'on_time'::character varying,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    stock integer NOT NULL,
    category_id integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.shipment_tracking
(
    shipment_id integer NOT NULL DEFAULT nextval('shipments_shipment_id_seq'::regclass),
    order_id integer,
    carrier character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tracking_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estimated_delivery date,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    location character varying(255) COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_id integer,
    CONSTRAINT shipments_pkey PRIMARY KEY (shipment_id),
    CONSTRAINT shipments_tracking_number_key UNIQUE (tracking_number)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('"Users_id_seq"'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(10) COLLATE pg_catalog."default" DEFAULT 'client'::character varying,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    verified boolean DEFAULT false,
    client_name character varying(100) COLLATE pg_catalog."default",
    contact_person character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    CONSTRAINT "Users_pkey" PRIMARY KEY (id),
    CONSTRAINT "Users_email_key" UNIQUE (email)
);

ALTER TABLE IF EXISTS public."Shipments"
    ADD CONSTRAINT "Shipments_clientId_fkey" FOREIGN KEY ("clientId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Shipments"
    ADD CONSTRAINT "Shipments_clientid_fkey" FOREIGN KEY (clientid)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_invoices_client_id
    ON public.invoices(client_id);


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.password_resets
    ADD CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_payments_user_id
    ON public.payments(user_id);


ALTER TABLE IF EXISTS public.shipment_tracking
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shipment_tracking
    ADD CONSTRAINT shipments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;